- name: play level variable
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: access URL in task 1
      ansible.builtin.debug:
        msg: URL in task 1 = {{URL}}

    - name: access URL in task 2
      ansible.builtin.debug:
        msg: URL in task 2 = {{URL}}
