#- name: play level variable
#  hosts: all
#  vars:
#    URL: play.example.com
#  tasks:
#    - name: access URL in task 1
#      ansible.builtin.debug:
#        msg: URL in task 1 = {{URL}}
#
#    - name: access URL in task 2
#      ansible.builtin.debug:
#        msg: URL in task 2 = {{URL}}
## declare variable in play level then all the tasks access that variable
#
#- name: demo on file variables
#  hosts: all
#  vars_files:
#    sample-vars.yml
#  tasks:
#    - name: access URL
#      ansible.builtin.debug:
#        msg: URL = {{URL}}
#
#- name: demo on task variables
#  hosts: all
#  tasks:
#    - name: access URL in task var
#      ansible.builtin.debug:
#        msg: URL = {{URL}}
#      vars:
#        URL: task.google.com
#
##    - name: access URL in previous task
##        ansible.builtin.debug:
##          msg: URL = {{URL}}
#
## if we declare variable in task, the variable works only that task.
#
#- name: demo on Inventory variables
#  hosts: all
#  tasks:
#    - name: access URL Invenroty
#      ansible.builtin.debug:
#        msg: URL = {{URL}}
#
#- name: demo on cli variabes
#  hosts: all
#  tasks:
#    - name: access URL cli
#      ansible.builtin.debug:
#        msg: URL = {{URL}}
#
#- name: demo on precedence
#  hosts: all
#  vars:
#    URL1: play.example.com
#  vars_files:
#    - sample-vars.yml
#  tasks:
#    - name: print URL1
#      ansible.builtin.debug:
#        msg: URL1 = {{URL1}}
#      vars:
#       URL1: task.google.com
#
#- name: print facts
#  hosts: all
#  vars:
#    ansible_distribution: sample
#  tasks:
#    - name: print a fact
#      ansible.builtin.debug:
#        msg: "HOST OS = {{ansible_distribution}}"

# we do not use ansible predefined variables, if used predefine variable is overwrite

- name: runtime variables
  hosts: all
  tasks:
    - name: get uptime command output
      ansible.builtin.shell: uptime
      register: OUT
# OUT is a variable
    - name: print OUT
      ansible.builtin.debug:
        msg: "{{OUT .stdout}}"

# no need of quotes while accessing and declare of variables
#quotes are required when start withs variables ex: {{URL}} hello
# when we use booleans in quotes it considered as string
#number quoted are not considered as  string. it considered as number only
