# tags are used to call perticular components only.
- name: demo on tags
  hosts: localhost
  tasks:
    - name: fruits
      ansible.builtin.debug:
        msg: fruits
      tags:
        - fruits
        - fruit
        - apple
    - name: groceries
      ansible.builtin.debug:
        msg: groceries
      tags:
        - groceries
        - veg