- name: demo on loops
  hosts: localhost
  fruits:
    vars: [ "apple", "banana", "pine" ]
  tasks:
    - name: print all fruits
      ansible.builtin.debug:
       msg: "fruit name = {{item}} "
      loop: "{{fruits}}"