- name: demo on loops
  hosts: localhost
  vars:
    fruits: [ "apple", "banana", "pine" ]
  tasks:
    - name: print all fruits
      ansible.builtin.debug:
       msg: "fruit name = {{item}} "
      loop: "{{fruits}}"

- name: demo on map values of loop
  hosts: localhost
  tasks:
    - name: print
      ansible.builtin.debug:
        msg: "course name = {{item.name}}, timing = {{item.timing}}"
      loop:
        - name: devops
          timing: 6am
        - name: aws
          timing: 8am
