- name: conditions
  hosts: localhost
  vars:
    URL: google.com
  tasks:
    - name: condition on string
      ansible.builtin.debug:
        msg: "{{URL}}"
      when: URL == "google.co in" or URL == "google.com"