- name: set up frontend
  hosts: frontend
  become: true
  tags: frontend
  roles:
    - frontend

- name: set up mongodb
  hosts: mongodb
  become: true
  tags: mongodb
  roles:
    - mongodb

- name: set up catalogue
  hosts: catalogue
  become: true
  tags: catalogue
  roles:
    - catalogue

- name: set up redis
  hosts: radis
  become: true
  tags: redis
  roles:
    - redis

