- name: Install nginx
  yum:
    name: nginx
    state: latest

- name: download code
  include_role:
    name: common
    tasks_from: download
  vars:
    APP_LOCATION: /usr/share/nginx/html/

- name: copy the Htdocs content
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: copy the roboshop.config files
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf


- name: start nginx
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes
