- name: Install nginx
  yum:
    name: nginx
    state: latest

- name: start nginx
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes

- name: download code
  include_role:
    name: common
    tasks_from: download