- name: setup MySQL repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: remove mariadb
  ansible.builtin.yum:
    name: mariadb-libs
    state: absent

- name: install MySQL
  ansible.builtin.yum:
    name:
      - mysql-community-server
      - MySQL-python
    state: present

- name: start MySQL server
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: grab default password
  ansible.builtin.shell: grep 'temporary passwdord' /var/log/mysqld.log | awk '{print $NF}'
  register: DEFAULT_PASSSWORD

- name: check the new password is working
  ansible.builtin.shell: echo 'show databases;' | mysql -uroot -p"{{NEW_PASSWORD}}"
  register: check_new_password
  ignore_errors: yes

- name: copy password reset sql file
  ansible.builtin.template:
    src: pass.sql
    dest: /tmp/pass.sql
  when: check_new_password.failed

- name: Reset password
  ansible.builtin.shell: mysql --connect-expired-password -uroot -p"{{DEFAULT_PASSWORD.stdout}}" </tmp/pass.sql
  when: check_new_password.failed
#
#- name: load schema
#  community.mysql.mysql_db:
#    state: import
#    name: all
#    target: /tmp/mysql-main/shipping.sql
#    login_user: root
#    login_password: "{{NEW_PASSWORD}}"
