
- name: install nodejs
  ansible.builtin.yum:
    name: [ "nodejs", "make", "gcc-c++"]
    state: present

- name: add roboshop app user
  ansible.builtin.user:
    name: roboshop

- name: download code
  include_role:
    name: common
    tasks_from: download

- name: remove existing code
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: copy app code
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue
    remote_src: true
  become_user: roboshop

- name: Install nodejs dependencies
  community.general.npm:
    path:  /home/roboshop/catalogue
  become_user: roboshop

- name: update systemd file
  template:
    src: systemd
    dest: /etc/systemd/system/catalogue.service

- name: start catalogue service
  ansible.builtin.systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon_reload: yes
