
- name: install nodejs
  ansible.builtin.yum:
    name: [ "nodejs", "make", "gcc-c++"]
    state: present

- name: download code
  ansible.builtin.include_role:
    name: common
    tasks_from: download
  vars:
    APP_LOCATION: /home/roboshop/{{COMPONENT}}

- name: Install nodejs dependencies
  community.general.npm:
    path:  /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: update systemd file
  template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: start {{COMPONENT}} service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes
